// Thu/Fri – Group 1
export const groupThuFri1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Diana T',
  'Elnaz',
  'Evert Markus Sirendi',
  'Fanny Leon',
  'Hans Tai',
  'Isak Unogwu',
  'Jacklyn Talm',
  'Josefin Maria T',
  'Joss Thao',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'MatteMai',
  'Mimmi',
  'Nikolas Ramža',
  'Oona Spara',
  'Pilar Padron',
  'Pillerin Arge',
  'Puya',
  'Robin Sabazade',
  'Ruta',
  'Sami Harju',
  'Sarah Nzau',
  'Sebastian Björkman',
  'Seng han lim',
  'Shuri li',
  'Teemu K',
  'Theresa Gustavsson',
  'Tobias Ramberg',
  'Trine Kjøsnes',
  'Willer',
  'William Bois',
];

// Thu/Fri – Group 2
export const groupThuFri2 = [
  'Agnes Andersson',
  'Andrei Misukka',
  'Anna Wroz',
  'Aura Huang',
  'Birgitta',
  'Cheuk Kei Charley Lam (SKY)',
  'Danys Van',
  'Denis Petrov',
  'Eemil Nummi',
  'Eli Keery',
  'Elisa Ofria',
  'Elsa Lundqvist',
  'Emil Johansson',
  'Emil Tamang',
  'Emmy Ohlsson',
  'Evert Markus Sirendi',
  'Eliace',
  'Hiu Shuen TSE',
  'Hilma Hakkebo',
  'Henri Ollikainen',
  'Ippi Iris Arjanne',
  'Joona Kontula',
  'Jenna Mäkinen',
  'Joshia Tan (+1)',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristi Bevan',
  'Kristian Autio',
  'Kristina Abelli',
  'Laura Kyllönen',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mayo N',
  'Mikael Koivula',
  'Nadja Boson',
  'Nataniel',
  'Niko Karppinen',
  'Nova Skeri',
  'Oda Reitaas',
  'Ole B Sondal',
  'Olea Huuska',
  'Olav',
  'Olav Juberg',
  'Oscar Sandmark',
  'Oona Korhonen',
  'Paula Uitto',
  'Rebecca N',
  'Roble Adare',
  'Ronja Simone',
  'Sabina Nowakowska',
  'Sara J',
  'Selim Reboudi',
  'Sergei P',
  'Shirley',
  'Simon Hälldal',
  'Theodor Strømmen',
  'Valdemar Larsson',
  'Valeria D',
  'Vide h p',
  'William A (Albinsson)',
];

// Sat/Sun – Group 1
export const groupSatSun1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Diana T',
  'Elnaz',
  'Elsa Lundqvist',
  'Fanny Leon',
  'Hans Tai',
  'Hiu Shuen TSE',
  'Isak Unogwu',
  'Josefin Maria T',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'MatteMai',
  'Mimmi',
  'Nikolas Ramža',
  'Oona Spara',
  'Puya',
  'Robin Sabazade',
  'Ruta',
  'Sami Harju',
  'Sarah Nzau',
  'Seng han lim',
  'Shuri li',
  'Teemu K',
  'Tobias Ramberg',
  'Theresa Gustavsson',
  'William Bois',
  'Willer',
];

// Sat/Sun – Group 2
export const groupSatSun2 = [
  'Andrei Misukka',
  'Birgitta',
  'Eemil Nummi',
  'Eli Keery',
  'Emil Johansson',
  'Emil Tamang',
  'Emmy Ohlsson',
  'Henri Ollikainen',
  'Jenna Mäkinen',
  'Joshia Tan',
  'Joss Thao',
  'Kristi Bevan',
  'Laura Kyllönen',
  'Nadja Boson',
  'Nataniel',
  'Niko Karppinen',
  'Nova Skeri',
  'Ole B Sondal',
  'Olav Juberg',
  'Olea Huuska',
  'Oona Korhonen',
  'Pillerin Arge',
  'Rebecca N',
  'Sabina Nowakowska',
  'Sara J',
  'Shirley',
  'Valeria,D',
];

// Sat/Sun – Group 3
export const groupSatSun3 = [
  'Agnes Andersson',
  'Anna Wroz',
  'Aura Huang',
  'Cheuk Kei Charley Lam (SKY)',
  'Danys Van',
  'Denis Petrov',
  'Elisa Ofria',
  'Evert Markus Sirendi',
  'Hilma Hakkebo',
  'Ippi Iris Arjanne',
  'Jacklyn Talm',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristian Autio',
  'Kristina Abelli',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mayo N',
  'Mikael Koivula',
  'Oda Reitaas',
  'Olav',
  'Oscar Sandmark',
  'Paula Uitto',
  'Pilar Padron',
  'Roble Adare',
  'Ronja Simone',
  'Sebastian Björkman',
  'Selim Reboudi',
  'Sergei P',
  'Simon Hälldal',
  'Theodor Strømmen',
  'Trine Kjøsnes',
  'Valdemar Larsson',
  'Vide h p',
  'William A (Albinsson)',
];
