export const groupThuFri1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Diana T',
  'Elnaz',
  'Emil Tamang',
  'Elsa Lundqvist',

  'Fanny Leon',
  'Hans Tai',
  'Hilma Hakkebo',
  'Isak Unogwu',
  'Jacklyn Talm',
  'Josefin Maria T',
  'Joss Thao',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'MatteMai',
  'Mimmi',
  'Nikolas Ramža',
  'Noah',
  'Oda Reitaas',
  'Ole B Sondal',
  'Olav Juberg',
  'Oona Spara',
  'Oscar Sandmark',
  'Pilar Padron',
  'Pillerin Arge',
  'Puya',
  'Roble Adare',
  'Robin Sabazade',
  'Ronja Simone',
  'Ruta',
  'Sami Harju',
  'Sarah Nzau',
  'Sebastian Björkman',
  'Seng han lim',
  'Shuri li',
  'Teemu K',
  'Theodor Strømmen',
  'Theresa Gustavsson',
  'Tobias Ramberg',
  'Trine Kjøsnes',
  'Willer',
  'William Bois',
];

export const groupThuFri2 = [
  'Agnes Andersson',
  'Andrei Misukka',
  'Anna Wroz',
  'Aura Huang',
  'Birgitta',
  'Cheuk Kei Charley Lam (SKY)',
  'Danys Van',
  'Denis Petrov',
  'Eemil Nummi',
  'Eli Keery',
  'Elisa Ofria',
  'Emil Johansson',
  'Emmy Ohlsson',
  'Eliace',
  'Evert Markus Sirendi',
  'Henri Ollikainen',
  'Hiu Shuen TSE',
  'Ippi Iris Arjanne',
  'Jenna Mäkinen',
  'Joona Kontula',
  'Joshia Tan (+1)',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristi Bevan',
  'Kristian Autio',
  'Kristina Abelli',
  'Laura Kyllönen',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mayo N',
  'Mikael Koivula',
  'Nadja Boson',
  'Nataniel',
  'Niko Karppinen',
  'Nova Skeri',
  'Olav',
  'Olea Huuska',
  'Oona Korhonen',
  'Paula Uitto',
  'Rebecca N',
  'Sabina Nowakowska',
  'Sara J',
  'Selim Reboudi',
  'Sergei P',
  'Shirley',
  'Simon Hälldal',
  'Valdemar Larsson',
  'Valeria D',
  'Vide h p',
  'William A (Albinsson)',
];

export const groupSatSun1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Diana T',
  'Elnaz',
  'Elsa Lundqvist',
  'Fanny Leon',
  'Hiu Shuen TSE',
  'Isak Unogwu',
  'Josefin Maria T',
  'Joss Thao',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'MatteMai',
  'Mimmi',
  'Nikolas Ramža',
  'Oona Spara',
  'Puya',
  'Robin Sabazade',
  'Ruta',
  'Sami Harju',
  'Sarah Nzau',
  'Sebastian Björkman',
  'Seng han lim',
  'Shuri li',
  'Teemu K',
  'Theresa Gustavsson',
  'Tobias Ramberg',
  'William Bois',
  'Willer',
];

export const groupSatSun2 = [
  'Andrei Misukka',
  'Eemil Nummi',
  'Eli Keery',
  'Emil Johansson',
  'Emil Tamang',
  'Emmy Ohlsson',
  'Hans Tai',
  'Henri Ollikainen',
  'Hilma Hakkebo',
  'Jenna Mäkinen',
  'Joshia Tan',
  'Kristi Bevan',
  'Laura Kyllönen',
  'Nadja Boson',
  'Nataniel',
  'Niko Karppinen',
  'Noah',
  'Oda Reitaas',
  'Ole B Sondal',
  'Olav Juberg',
  'Olea Huuska',
  'Oona Korhonen',
  'Pillerin Arge',
  'Pilar Padron',
  'Rebecca N',
  'Roble Adare',
  'Ronja Simone',
  'Sabina Nowakowska',
  'Sara J',
  'Shirley',
  'Trine Kjøsnes',
  'Theodor Strømmen',
  'Valeria D',
];

export const groupSatSun3 = [
  'Agnes Andersson',
  'Anna Wroz',
  'Aura Huang',
  'Birgitta',
  'Cheuk Kei Charley Lam (SKY)',
  'Danys Van',
  'Denis Petrov',
  'Elisa Ofria',
  'Evert Markus Sirendi',
  'Ippi Iris Arjanne',
  'Jacklyn Talm',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristian Autio',
  'Kristina Abelli',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mayo N',
  'Mikael Koivula',
  'Olav',
  'Oscar Sandmark',
  'Paula Uitto',
  'Selim Reboudi',
  'Sergei P',
  'Simon Hälldal',
  'Valdemar Larsson',
  'Vide h p',
  'William A',
];
