export const groupThuFri1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Danys Van',
  'Diana T',
  'Elnaz',
  'Emil Tamang',
  'Elsa Lundqvist',
  'Fanny Leon',
  'Hilma Hakkebo',
  'Isak Unogwu',
  'Josefin Maria T',
  'Joss Thao',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'Mayo N',
  'Mettemai',
  'Mimmi',
  'Nikolas Ramža',
  'Oda Reitaas',
  'Ole B Sondal',
  'Olav Juberg',
  'Olav',
  'Oona Spara',
  'Oscar Sandmark',
  'Pilar Padron',
  'Puya',
  'Rebecca N',
  'Roble Adare',
  'Robin Sabazade',
  'Ronja Simone',
  'Ruta',
  'Sara J',
  'Sarah Nzau',
  'Selim Reboudi',
  'Seng han lim', 
  'Shurui li',
  'Teemu K',
  'Theodor Strømmen',
  'Theresa Gustavsson',
  'Tobias Ramberg',
  'Trine Kjøsnes',
  'Willer',
  'William Bois',
  'William A',
];

export const groupThuFri2 = [
  'Agnes Andersson',
  'Andrei Misukka',
  'Anna Wroz',
  'Aura Huang',
  'Birgitta',
  'Denis Petrov',
  'Eemil Nummi',
  'Eli Keery',
  'Hans Tai',
  'Sky',
  'Hiu Shuen TSE',
  'Elisa Ofria',
  'Emil Johansson',
  'Emmy Ohlsson',
  'Eliace',
  'Evert Markus Sirendi',
  'Henri Ollikainen',
  'Ippi Iris Arjanne',
  'Jacklyn Talm',
  'Jenna Mäkinen',
  'Joona Kontula',
  'Josiah',
  'Jogina',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristi Bevan',
  'Kristian Autio',
  'Kristina Abelli',
  'Laura Kyllönen',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mikael Koivula',
  'Nadja Boson',
  'Niko Karppinen',
  'Nova Skeri',
  'Olea Huuska',
  'Oona Korhonen',
  'Paula Uitto',
  'Pillerin Arge',
  'Sabina Nowakowska',
  'Sami Harju',
  'Sebastian Björkman',  
  'Sergei P',
  'Shirley',
  'Simon Hälldal',
  'Valdemar Larsson',
  'Valeria D',
  'Vide h p',
];

export const groupSatSun1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Danys Van',
  'Diana T',
  'Elnaz',
  'Elsa Lundqvist',
  'Fanny Leon',
  'Isak Unogwu',
  'Josefin Maria T',
  'Joss Thao',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'Mettemai',
  'Mimmi',
  'Nikolas Ramža',
  'Oona Spara',
  'Puya',
  'Robin Sabazade',
  'Ruta',  
  'Sarah Nzau',
  'Sebastian Björkman',
  'Selim Reboudi',
  'Seng han lim',
  'Shurui li',
  'Teemu K',
  'Theresa Gustavsson',
  'Tobias Ramberg',
  'William Bois',
  'Willer',
];

export const groupSatSun2 = [
  'Aura Huang',
  'Emil Johansson',
  'Emil Tamang',
  'Emmy Ohlsson',
  'Eli Keery',
  'Eliace',
  'Hans Tai',
  'Sky',
  'Hiu Shuen TSE',
  'Hilma Hakkebo',
  'Jenna Mäkinen',
  'Joona Kontula',
  'Josiah',
  'Jogina',
  'Kristi Bevan',
  'Laura Kyllönen',
  'Mayo N',
  'Oda Reitaas',
  'Ole B Sondal',
  'Olav Juberg',
  'Olav',
  'Oscar Sandmark',
  'Paula Uitto',
  'Pillerin Arge',
  'Pilar Padron',
  'Rebecca N',
  'Roble Adare',
  'Ronja Simone',
  'Sabina Nowakowska',
  'Sara J',
  'Shirley',
  'Trine Kjøsnes',
  'Theodor Strømmen',
  'William A',
];

export const groupSatSun3 = [
  'Andrei Misukka',
  'Agnes Andersson',
  'Anna Wroz',
  'Birgitta',
  'Denis Petrov',
  'Eemil Nummi',
  'Elisa Ofria',
  'Evert Markus Sirendi',
  'Ippi Iris Arjanne',
  'Henri Ollikainen',
  'Jacklyn Talm',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristian Autio',
  'Kristina Abelli',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mikael Koivula',
  'Nadja Boson',
  'Nova Skeri',
  'Niko Karppinen',
  'Olea Huuska',
  'Oona Korhonen',
  'Sami Harju',
  'Sergei P',
  'Simon Hälldal',
  'Valdemar Larsson',
  'Vide h p',
  'Valeria D',
];
