// Thu/Fri – Group 1
export const groupThuFri1 = [
  'Alice Speroni',
  'Alma Hakim',
  'Brian Mihalíček',
  'Diana T',
  'Elnaz',
  'Evert Markus Sirendi',
  'Fanny Leon',
  'Hans Tai',
  'Isak Unogwu',
  'Jacklyn Talm',
  'Josefin Maria T',
  'Joss Thao',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'MatteMai',
  'Mimmi',
  'Nikolas Ramža',
  'Oona Spara',
  'Pilar Padron',
  'Pillerin Arge',
  'Robin Sabazade',
  'Ruta',
  'Sami Harju',
  'Sarah Nzau',
  'Sebastian Björkman',
  'Seng han lim',
  'Shuri li',
  'Teemu K',
  'Theresa Gustavsson',
  'Tobias Ramberg',
  'Trine Kjøsnes',
  'Willer',
  'William Bois',
];

// Thu/Fri – Group 2
export const groupThuFri2 = [
  'Agnes Andersson',
  'Andrei Misukka',
  'Anna Wroz',
  'Aura Huang',
  'Basel',
  'Birgitta',
  'Cheuk Kei Charley Lam (SKY)',
  'Danys Van',
  'Denis Petrov',
  'Eemil Nummi',
  'Eli Keery',
  'Elisa Ofria',
  'Elsa Lundqvist',
  'Emil Johansson',
  'Emil Tamang',
  'Emmy Ohlsson',
  'Hiu Shuen TSE',
  'Hilma Hakkebo',
  'Henri Ollikainen',
  'Ippi Iris Arjanne',
  'Joona Kontula',
  'Jenna Mäkinen',
  'Joshia Tan (+1)',
  'Judy Liu',
  'Kasper Kuparinen',
  'Kristi Bevan',
  'Kristian Autio',
  'Kristina Abelli',
  'Laura Kyllönen',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mayo N',
  'Mettemai',
  'Mikael Koivula',
  'Nadja Boson',
  'Nataniel',
  'Niko Karppinen',
  'Nira ???',
  'Nova Skeri',
  'Oda Reitaas',
  'Ole B Sondal',
  'Olea Huuska',
  'Olav',
  'Olav Juberg',
  'Oscar Sandmark',
  'Oona Korhonen',
  'Paula Uitto',
  'Puya',
  'Rebecca N',
  'Roble Adare',
  'Ronja Simone',
  'Sabina Nowakowska',
  'Sara J',
  'Selim Reboudi',
  'Sergei P',
  'Shirley',
  'Simon Hälldal',
  'Theodor Strømmen',
  'Valdemar Larsson',
  'Valeria,D',
  'Vide h p',
  'William A (Albinsson)',
];

// Sat/Sun – Group 1
export const groupSatSun1 = [
  'Agnes Andersson',
  'Alma Hakim',
  'Cheuk Kei Charley Lam (SKY)',
  'Diana T',
  'Eli Keery',
  'Emmy Ohlsson',
  'Fanny Leon',
  'Hans Tai',
  'Hilma Hakkebo',
  'Hiu Shuen TSE',
  'Isak Unogwu',
  'Joshia Tan (+1)',
  'Judy Liu',
  'Jörgen',
  'Kertu Kase',
  'Loke Wadström',
  'Malva N',
  'MatteMai',
  'Nova Skeri',
  'Olav Juberg',
  'Oona Spara',
  'Pillerin Arge',
  'Sarah Nzau',
  'Seng han lim',
  'Shirley',
  'Shuri li',
  'Teemu K',
  'Tobias Ramberg',
  'Valeria,D',
];

// Sat/Sun – Group 2
export const groupSatSun2 = [
  'Andrei Misukka',
  'Basel',
  'Birgitta',
  'Eemil Nummi',
  'Elnaz',
  'Emil Johansson',
  'Emil Tamang',
  'Henri Ollikainen',
  'Jenna Mäkinen',
  'Josefin Maria T',
  'Joss Thao',
  'Kristi Bevan',
  'Laura Kyllönen',
  'Mimmi',
  'Nadja Boson',
  'Nataniel',
  'Niko Karppinen',
  'Ole B Sondal',
  'Olea Huuska',
  'Oona Korhonen',
  'Puya',
  'Rebecca N',
  'Ruta',
  'Sabina Nowakowska',
  'Sami Harju',
  'Sara J',
  'Theresa Gustavsson',
  'Trine Kjøsnes',
  'William Bois',
];

// Sat/Sun – Group 3
export const groupSatSun3 = [
  'Alice Speroni',
  'Anna Wroz',
  'Aura Huang',
  'Brian Mihalíček',
  'Danys Van',
  'Denis Petrov',
  'Elisa Ofria',
  'Elsa Lundqvist',
  'Evert Markus Sirendi',
  'Ippi Iris Arjanne',
  'Jacklyn Talm',
  'Kasper Kuparinen',
  'Kristian Autio',
  'Kristina Abelli',
  'Lenel Karu',
  'Lilian Kallo',
  'Mari Pulkkinen',
  'Martin Arango',
  'Mayo N',
  'Mikael Koivula',
  'Nikolas Ramža',
  'Oda Reitaas',
  'Olav',
  'Oscar Sandmark',
  'Paula Uitto',
  'Pilar Padron',
  'Robin Sabazade',
  'Roble Adare',
  'Ronja Simone',
  'Sebastian Björkman',
  'Selim Reboudi',
  'Sergei P',
  'Simon Hälldal',
  'Theodor Strømmen',
  'Valdemar Larsson',
  'Vide h p',
  'William A (Albinsson)',
  'Willer',
];
